name: qlora-unsloth-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - python-dotenv==1.2.1
      - unsloth==2026.2.1
      - wandb==0.25.0
      - pandas==3.0.1
      - datasets==4.3.0
      - trl==0.24.0
